doctrine:
    dbal:
        # configure these for your database server

        driver: 'pdo_mysql'
        #server_version: '5.7'
        charset: utf8mb4
        override_url: true
        url: '%env(resolve:DATABASE_URL)%'
        types:
            json: Sonata\Doctrine\Types\JsonType
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        dql:
            string_functions:
                NOW: DoctrineExtensions\Query\Mysql\Now
                DATE: DoctrineExtensions\Query\Mysql\Date
                MONTH: DoctrineExtensions\Query\Mysql\Month
                YEAR: DoctrineExtensions\Query\Mysql\Year
                FORMAT: DoctrineExtensions\Query\Mysql\Format
                REPLACE: DoctrineExtensions\Query\Mysql\Replace
                DATE_FORMAT: DoctrineExtensions\Query\Mysql\DateFormat
            numeric_functions:
                RAND: DoctrineExtensions\Query\Mysql\Rand
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true

        mappings:
            SonataUserBundle: ~
            FOSUserBundle: ~
            ApplicationSonataUserBundle: ~
            SonataMediaBundle: ~
            ApplicationSonataMediaBundle: ~

            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

            # /////////////////////////////// #

