# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
# app/config/config.yml
fos_ck_editor:
    configs:
        my_config_1:
            language: pt_BR
            toolbar: basic
        my_config_2:
            language: pt_BR
            toolbar: standard
        my_config_3:
            language: pt_BR
            toolbar: full